import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import TopHeader from "@/components/common/TopHeader";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import { ScrollProvider } from "@/context/ScrollProvider";
import { ExploreScrollProvider } from "@/context/ExploreScrollProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // choose weights you need
  variable: "--font-poppins", // adds a CSS variable for Tailwind
});



export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />

      
      </head>
      <body
        className={`${poppins.variable}  antialiased w-[100%] h-auto mx-auto`}
      >
        <ExploreScrollProvider>
          <ScrollProvider>
            <TopHeader/>
            <Header/>
            {children}
            <Footer/>
          </ScrollProvider>
        </ExploreScrollProvider>
          
        
        
        
       
        
      </body>
    </html>
  );
}
